### PR TITLE
create solr schema for unirule

### PR DESCRIPTION
**Pull request by sahmad-ebi**
@jieluo321 Fields are listed here https://www.ebi.ac.uk/panda/jira/browse/TRM-24026

### CODE REVIEW

**Comment by jluo321** [comment]
organism, taxonomy and keyword to be autocomplete
go_* should not be dynamic. we can just have search term such as go (used by uniprotkb)

go can also be autocomplete. 

For autocomplete fields, do we need to have a single field or two fields for each one (one exact, and full_ci) (this is what we have for uniprotkb). For unirule, i think it is enough to have only one field defined as full_ci.

**Comment by jluo321** [comment]
we will need to total protein count for each rule

**Comment by sahmad-ebi** [comment]
> we will need to total protein count for each rule

I will add the count in the UniRuleEntry model. And that model object will be stored in solr.

**Comment by sahmad-ebi** [comment]
> organism, taxonomy and keyword to be autocomplete
> go_* should not be dynamic. we can just have search term such as go (used by uniprotkb)
> 
> go can also be autocomplete.
> 
> For autocomplete fields, do we need to have a single field or two fields for each one (one exact, and full_ci) (this is what we have for uniprotkb). For unirule, i think it is enough to have only one field defined as full_ci.

@jieluo321 I have made the changes. Can you please see the schema.xml file? thanks.

**Comment by jieluo321** [comment]
Looks ok. We need to Sangya to confirm about feature_type one. If we use this, this one is also going to autocomplete with a list of feature types supported

**Pull request merged**
